# Generated by Django 4.2.3 on 2023-08-30 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_alter_student_address_alter_student_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_user', to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
    ]
