# Generated by Django 4.2.3 on 2023-08-31 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_reportcode_code_reportcode_consecutive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcode',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='reportcode',
            name='consecutive',
            field=models.IntegerField(default=1000001, editable=False),
        ),
        migrations.DeleteModel(
            name='Consecutive',
        ),
    ]
