# Generated by Django 4.2.3 on 2023-08-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_reportcode_code_alter_reportcode_consecutive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcode',
            name='consecutive',
            field=models.BigIntegerField(default=1000001, editable=False),
        ),
    ]
