# Generated by Django 4.2.3 on 2023-08-31 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_reportcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcode',
            name='code',
        ),
        migrations.AddField(
            model_name='reportcode',
            name='internal_code',
            field=models.CharField(default=uuid.uuid4, max_length=32, unique=True),
        ),
    ]
