# Generated by Django 4.2.3 on 2023-08-02 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, choices=[('N/A', 'No agignado'), ('S1A', 'Primero A'), ('S1B', 'Primero B'), ('S1C', 'Primero C'), ('S2A', 'Segundo A'), ('S2B', 'Segundo B'), ('S2C', 'Segundo C'), ('S3A', 'Tercero A'), ('S3B', 'Tercero B'), ('S3C', 'Tercero C'), ('S4A', 'Cuarto A'), ('S4B', 'Cuarto B'), ('S4C', 'Cuarto C'), ('S5A', 'Quinto A'), ('S5B', 'Quinto B'), ('S5C', 'Quinto C'), ('S6A', 'Sexto A'), ('S6B', 'Sexto B'), ('S6C', 'Sexto C')], default='N/A', max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'evaluation',
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, editable=False, null=True)),
                ('month', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluation_qualification', to='qualification.evaluation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qualification_user', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_qualification', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluationcriteria_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'evaluationcriteria',
                'db_table': 'evaluationcriteria',
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='criteria',
            field=models.ManyToManyField(related_name='evaluationcriteria_evaluation', to='qualification.evaluationcriteria'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluation_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
