# Generated by Django 4.2.3 on 2023-08-02 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualification', '0002_alter_evaluation_options_alter_qualification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunctuationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_criteria', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='punctuationcriteria_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'punctuationcriteria',
                'db_table': 'punctuationcriteria',
            },
        ),
        migrations.CreateModel(
            name='Punctuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluation_punctuation', to='qualification.evaluation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='punctuation_user', to=settings.AUTH_USER_MODEL)),
                ('values', models.ManyToManyField(related_name='punctuationcriteria_punctuation', to='qualification.punctuationcriteria')),
            ],
            options={
                'verbose_name_plural': 'punctuations',
                'db_table': 'punctuation',
            },
        ),
    ]
