# Generated by Django 4.2.3 on 2023-08-02 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0005_qualification_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='month',
        ),
        migrations.AddField(
            model_name='qualification',
            name='date',
            field=models.DateField(default=None, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualification',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='penalty',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0, message='El valor debe ser mayor o igual a 0.0'), django.core.validators.MaxValueValidator(limit_value=100.0, message='El valor debe ser menor o igual a 100.0')], verbose_name='Penalización'),
        ),
    ]
