# Generated by Django 4.2.3 on 2023-08-30 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_alter_student_owner'),
        ('qualification', '0007_alter_qualification_final_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qualification_user', to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_qualification', to='student.student', verbose_name='Estudiante'),
        ),
    ]
