# Generated by Django 4.2.3 on 2023-08-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0009_achievementindicator_fundamentalcompetencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='fundamental_competencies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qualification.fundamentalcompetencies'),
        ),
    ]
