# Generated by Django 4.2.3 on 2023-08-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0010_alter_qualification_fundamental_competencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='fundamental_competencies',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='qualification.fundamentalcompetencies'),
            preserve_default=False,
        ),
    ]
